export const objectOne = {
    id: 'one',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine:'About Me',
    headline: 'Developer & Designer',
    description: `I am a recent grad seeking employment opportunities. I believe that design should not impede the speed users absorb information and that sometimes a simple layout is best to convey information.`,
    buttonLabel: 'Next',
    direct: 'two',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Image',
    dark: true,
    primary: true,
    darkText: false,
}

export const objectTwo = {
    id: 'two',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine:'Skills',
    headline: 'Software',
    description: `Some of the technologies I have worked with includes the MERN stack. This portfolio website was created using Gatsby.`,
    buttonLabel: 'Next',
    direct: 'animation',
    imgStart: true,
    img: require('../../images/Skills.svg'),
    alt: 'Image',
    dark: false,
    primary: false,
    darkText: true,
}
